# Generated by Django 3.1 on 2020-08-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('Further Maths', 'Further Maths'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('Computer Science', 'Computer Science'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
