# Generated by Django 3.1 on 2020-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('Further Maths', 'Further Maths'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('Computer Science', 'Computer Science'), ('Japanese', 'Japanese'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
